[package]
name = "matix"
version = "0.1.0"
edition = "2021"

[features]
f32 = []
f64 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.3.1"
rand = "0.8.5"
